### ISSUE TITLE
empty file upload result in internet browser.

### ISSUE THREAD

**Issue by vikashshukla** [i-e-b/jQueryFileUpload.Net#19]
empty file upload result in internet browser. Drag and Drop file upload not working IE, but select files working fine in IE also.

**Comment by i-e-b** [comment]
Drag-and-drop does not work in IE due to shortcomings in that browser.

**Comment by vikashshukla** [comment]
We remove this check 'typeof XMLHttpRequestUpload !== undef’ from the function '_isXHRUpload: function (options)’ in ‘jquery.fileupload.js’ page, now Drag And Drop working fine in Internet Explorer also. But Not sure removing this check will effect anything else.

**Comment by i-e-b** [comment]
That should be submitted to https://github.com/blueimp/jQuery-File-Upload

This repository is just for the server-side code for ASP.Net (and is quite out of date)
