### ISSUE TITLE
Have problem with progress bar in the IE browser

### ISSUE THREAD

**Issue by tranphuongyd** [i-e-b/jQueryFileUpload.Net#20]
Hi, 
I have a problem when I use IE 11 and upload multi file but show only first progress bar. Not show all progress for earch file.
![1122](https://cloud.githubusercontent.com/assets/7795756/6922870/72227652-d7f8-11e4-8f5f-0a2f14fa05a9.png)

Thanks

**Comment by i-e-b** [comment]
Hi. Do you get different behaviour with other browsers? Are there any console messages being written?

**Comment by tranphuongyd** [comment]
Hi @i-e-b , I tried with Chrome and Firefox, that work very well but on IE browser has this problem. Then I open the console but nothing error written. You can download it and try with IE browser. 

Thanks

**Comment by i-e-b** [comment]
This is most likely a problem between the Javascript part and IE. Try the latest javascript from https://github.com/blueimp/jQuery-File-Upload. If you still have trouble, please raise an issue there.

This repository is for the Server-side support on ASP.net, I don't maintain any of the client side code.

**Comment by tranphuongyd** [comment]
Thanks @i-e-b
