### ISSUE TITLE
Keeps on adding same name file to the list

### ISSUE THREAD

**Issue by himanshu1007** [i-e-b/jQueryFileUpload.Net#21]
If I try uploading same file (i.e. same name), though only single file is sent to the server and replaced with latest (working fine), the list on the browser keeps on adding same file name, as a result the list in the browser grows, though actual upload is only 1.

I think the list should reset at each upload start.

**Comment by i-e-b** [comment]
This repository is for the server side, not the browser side. Please submit browser specific queries to the main jQueryUpload repository.

**Comment by himanshu1007** [comment]
Hi i-e-b

The problem is if I update the jQueryUpload scripts, the code breaks down completely.
If possible please look into it.

**Comment by i-e-b** [comment]
Sorry, I don't really maintain this project any more. There are alternatives at https://github.com/blueimp/jQuery-File-Upload/wiki#aspnet
